name: Deployment Workflow

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        name: Deploy on production server
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/SpookyBot/
            git pull --ff-only
            docker-compose -f ~/SpookyBot/docker-compose.yml down -v
            docker-compose -f ~/SpookyBot/docker-compose.yml up --build -d
